# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: abumalick/alpine-python-pipenv-postgres:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: learn_islam
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: debug
  POSTGRES_PASSWORD: debug
  DATABASE_URL: 'postgres://debug:debug@postgres:5432/learn_islam'
  USE_DOCKER: 'no'
  IPYTHONDIR: '/app/.ipython'
  CELERY_FLOWER_USER: 'debug'
  CELERY_FLOWER_PASSWORD: 'debug'
  REDIS_URL: 'redis://redis:6379/0'
  CELERY_BROKER_URL: 'TODO'

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pipenv

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python -V # Print out python version for debugging
  - pipenv install --system --deploy --dev

test:
  script:
    - python manage.py test
