# Generated by Django 2.0.10 on 2019-01-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20190126_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.URLField(blank=True, max_length=255, verbose_name='Audio')),
                ('duration', models.PositiveIntegerField(blank=True, verbose_name='Duration')),
                ('level', models.PositiveIntegerField(blank=True, verbose_name='Level')),
                ('order', models.PositiveIntegerField(blank=True, verbose_name='Order')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='Slug')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('locale', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('transcription', models.TextField(blank=True, verbose_name='Transcription')),
                ('video', models.CharField(max_length=40, verbose_name='Video')),
                ('vocabulary', models.TextField(blank=True, verbose_name='Vocabulary')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chapters.Chapter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chaptertranslation',
            unique_together={('locale', 'chapter')},
        ),
    ]
