# Generated by Django 2.0.10 on 2019-01-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_auto_20190126_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='level',
        ),
    ]
