# Generated by Django 2.0.10 on 2019-02-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_remove_chapter_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
    ]
