# Generated by Django 2.0.10 on 2019-02-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_auto_20190203_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptertranslation',
            name='description',
        ),
    ]
