# Generated by Django 2.0.10 on 2019-05-19 17:49

import learn_islam.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_remove_chaptertranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptertranslation',
            name='locale',
            field=learn_islam.core.models.LocaleField(choices=[('ar', 'العربية'), ('fr', 'Français')], max_length=10, verbose_name='Language'),
        ),
    ]
