# Generated by Django 2.0.10 on 2019-01-26 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20190126_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveIntegerField(blank=True, verbose_name='Difficulty')),
                ('type', models.CharField(blank=True, max_length=20, verbose_name='Slug')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('locale', models.CharField(max_length=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quizzes.Quiz')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='quiztranslation',
            unique_together={('locale', 'quiz')},
        ),
    ]
