# Generated by Django 2.0.10 on 2019-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(blank=True, choices=[('choose', 'Choose the correct answer'), ('fill-in-the-blank', 'Fill in the blank'), ('link-the-sentences', 'Link the matching sentences'), ('choose-a-category', 'Choose the correct category'), ('true-or-false', 'Answer by true or false')], max_length=20, verbose_name='Type'),
        ),
    ]
