# Generated by Django 2.1.8 on 2019-05-26 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20190519_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Publication date'),
            preserve_default=False,
        ),
    ]
