# Generated by Django 2.0.10 on 2019-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, verbose_name='Order')),
                ('level', models.PositiveIntegerField(blank=True, verbose_name='Level')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='Slug')),
            ],
        ),
    ]
