# Generated by Django 2.0.10 on 2019-01-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('locale', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='level',
        ),
        migrations.AddField(
            model_name='tracktranslation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tracks.Track'),
        ),
        migrations.AlterUniqueTogether(
            name='tracktranslation',
            unique_together={('locale', 'track')},
        ),
    ]
