# Generated by Django 2.0.10 on 2019-05-19 17:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20190203_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracktranslation',
            name='locale',
            field=core.models.LocaleField(choices=[('ar', 'العربية'), ('fr', 'Français')], max_length=10, verbose_name='Language'),
        ),
    ]
