# Generated by Django 2.1.8 on 2019-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20190519_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='soon',
            field=models.BooleanField(blank=True, default=False, verbose_name='Coming Soon'),
        ),
    ]
